name: My first workflow

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
     - name: Install cowsay program
       run: sudo apt-get install cowsay -y
     - name: Excute cowsay CMD
       run: cowsay -f dragon "Run foe cover , I am dragon" >> dragon.txt
     - name: Upload dragon text file
       uses: actions/upload-artifact@v4
       with:
         name: dragon-text-file
         path: dragon.txt
  
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon text file
        uses: actions/download-artifact@v5
        with:
          name: dragon-text-file
        
      - name: Test file Exsist
        run: grep -i "dragon" dragon.txt
  
  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon text file
        uses: actions/download-artifact@v5
        with:
          name: dragon-text-file
      - name: Read file
        run: cat dragon.txt
      - name: Deploy
        run: echo deploying ....         



